- .github/workflows/02-build-obs.yml
放到obs集成项目的package中初始化,避免集成没有完成的情况下Testing项目中包含了一个源码和软件包版本
> feat: _service文件初始化流程优化

- .github/workflows/02-build-obs.yml
link机制在已有_branch_request文件的情况下更新并不能更新代码,因此取消
> fix(CI): obs pacakge link error

- intergration.yml
目前大家好像都不修改默认的集成信息，暂时在模板里面修改默认信息，避免bata集成的issue标题里面带preview的信息
> feat(CI): Change default integration message

- .github/workflows/obs-proj-meta.tpl
集成project关闭自动rebuild，避免多少架构版本号差异问题
> disable auto rebuild

- .github/workflows/auto-intergration.yml
> chore: intergration repo address add copy support

- .github/workflows/01-parsec-integration.yml
cased of obs request auto merge hang on
> fix(CI): read integration message is null

- .github/workflows/01-parsec-integration.yml
- .github/workflows/README.md
- .github/workflows/auto-integration.yml
- .github/workflows/issue-project-manager.yml
> fix(CI): spell error

- .github/workflows/06-deployed.yml
- .github/workflows/07-sync-integration-info.yml
- .github/workflows/issue-project-manager.yml
> fix(CI): github scripts get token error

- .github/workflows/01-parsec-integration.yml
if integration message isn't modified,use pr title as integration message
> chore(CI): enhance integration workflow

- .github/workflows/issue-project-manager.yml
/cc @Zeno-sole @xzl01 
集成管理项目在集成单创建后添加时间记录。
> feat(CI): integration project add 'Date Created' field  to record intgration start time

- .github/workflows/issue-project-manager.yml
> fix(CI): Update integration 'Date Created' filed error

- .github/workflows/01-parsec-integration.yml
> fix(CI): override integrate message to issue incorrect

- .github/workflows/02-build-obs.yml
use osc api get build status
log:
> fix(CI): Get integrate build incorrect

- .github/workflows/02-build-obs.yml
the finished status is also successed
log:
> fix(CI): Get integrate build status incorrect

- .github/workflows/integration-clean.yml
> feat(CI): Add clean step when integration end

- .github/workflows/01-parsec-integration.yml
- .github/workflows/auto-integration.yml
对应未修改changelog的情况下的预集成和测试的状况
log:
> feat(CI): integration add 'Project:Pre-integrated' status

- .github/workflows/auto-integration.yml
已经关闭的issue生命周期已经走完，需要重新创建issue，不管是否为解决相同问题的pr.
> chore(CI): Create new integration issue when integration pr's issuse closed

- .github/workflows/auto-integration.yml
> chore(CI): fix remove build order error

- .github/workflows/auto-integration.yml
必须在pass_integration通过后运行该步骤
log:
> chore(CI): fix close-pull-request step error

- .github/workflows/02-build-obs.yml
> fix(CI): Get obs log error when package component isn't main

- .github/workflows/02-build-obs.yml
github commit status更新通过[k3s canal](https://github.com/deepin-community/infra-settings/tree/master/services/canal)服务更新。
> chore(CI): Use github commit status sync integrate workflow

- .github/workflows/06-deployed.yml
- .github/workflows/07-sync-integration-info.yml
- .github/workflows/issue-project-manager.yml
新版本require存在问题,需要等https://github.com/octokit/octokit.js/pull/2665 合并才能正常
> fix(CI): use old octokit version to support require

- .github/workflows/01-parsec-integration.yml
- .github/workflows/02-build-obs.yml
- .github/workflows/auto-integration.yml
借助obs的项目隐藏功能和build.script实现商业项目的源码不可见需求
备注: 1. integration.yml添加gitaddr字段,在商业组件集成过程中添加这个字段指定需要该组件的git ssh源码地址,obs服务通过ssh拉去源码
2. 商业组件目前不支持自动获取changelog,集成单需要自行备注
> feat: add commercial package support

- .github/workflows/02-build-obs.yml
> chore: change obs commercial project access permission

- integration.yml
Reverts deepin-community/Repository-Integration#2150
> Revert "auto integration deepin-community/polkit-qt-1"

- integration.yml
Reverts deepin-community/Repository-Integration#2611
> Revert "auto integration deepin-community/gcc-12"
